Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%load_ext autoreload
%autoreload 2
import os
from collections import Counter, defaultdict

import dimcat as dc
import ms3
import pandas as pd
import plotly.express as px
from dimcat import plotting
from dimcat.steps import filters, groupers, slicers

import utils
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 13[39m
[32m     10[39m [38;5;28;01mfrom[39;00m [34;01mdimcat[39;00m [38;5;28;01mimport[39;00m plotting
[32m     11[39m [38;5;28;01mfrom[39;00m [34;01mdimcat[39;00m[34;01m.[39;00m[34;01msteps[39;00m [38;5;28;01mimport[39;00m filters, groupers, slicers
[32m---> [39m[32m13[39m [38;5;28;01mimport[39;00m [34;01mutils[39;00m

[36mFile [39m[32m~/work/workflow_deployment/wagner_overtures/tmp_corpus_docs/notebooks/utils.py:34[39m
[32m     32[39m [38;5;28;01mimport[39;00m [34;01mpandas[39;00m [38;5;28;01mas[39;00m [34;01mpd[39;00m
[32m     33[39m [38;5;28;01mimport[39;00m [34;01mplotly[39;00m[34;01m.[39;00m[34;01mexpress[39;00m [38;5;28;01mas[39;00m [34;01mpx[39;00m
[32m---> [39m[32m34[39m [38;5;28;01mimport[39;00m [34;01mseaborn[39;00m [38;5;28;01mas[39;00m [34;01msns[39;00m
[32m     35[39m [38;5;28;01mfrom[39;00m [34;01mdimcat[39;00m [38;5;28;01mimport[39;00m Dataset
[32m     36[39m [38;5;28;01mfrom[39;00m [34;01mdimcat[39;00m[34;01m.[39;00m[34;01mbase[39;00m [38;5;28;01mimport[39;00m FriendlyEnum, deserialize_json_file, get_setting

[31mModuleNotFoundError[39m: No module named 'seaborn'

